#!/usr/bin/env bash
# momo worktree bootstrap for Conductor and manual git-worktree flows.
# Safe to re-run. Generated env files are intentionally ignored.
set -euo pipefail

current_root="$(git rev-parse --show-toplevel)"
common_dir="$(git rev-parse --path-format=absolute --git-common-dir)"

# In a linked worktree, --git-common-dir points at the primary checkout's .git.
# In the primary checkout, dirname(.git) is the repo root.
primary_root="$(dirname "$common_dir")"
if [ ! -f "$primary_root/infra/.env.example" ]; then
  primary_root="$current_root"
fi

raw_name="${CONDUCTOR_WORKSPACE_NAME:-$(basename "$current_root")}"
branch_name="$(git branch --show-current 2>/dev/null || true)"
if [ -n "$branch_name" ]; then
  raw_name="$branch_name"
fi

safe_name="$(
  printf '%s' "$raw_name" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g'
)"
if [ -z "$safe_name" ]; then
  safe_name="local"
fi

if [ "${CONDUCTOR_PORT:-}" != "" ]; then
  base_port="$CONDUCTOR_PORT"
else
  hash_value="$(printf '%s' "$safe_name" | cksum | awk '{print $1}')"
  base_port=$((18000 + (hash_value % 1000) * 10))
fi

api_port="${PORT:-$base_port}"
cent_port="${CENT_PORT:-$((base_port + 1))}"
postgres_port="${POSTGRES_PORT:-$((base_port + 2))}"
hermes_port="${HERMES_PORT:-$((base_port + 3))}"
compose_project="momo_${safe_name}"

mkdir -p .conductor

# Keep secrets in the primary checkout. Do not copy .env into worktrees.
if [ "$primary_root" != "$current_root" ] && [ -f "$primary_root/.env" ] && [ ! -e "$current_root/.env" ]; then
  ln -s "$primary_root/.env" "$current_root/.env"
  echo "linked .env -> $primary_root/.env"
fi

base_env="$current_root/infra/.env.example"
if [ -f "$current_root/.env" ]; then
  base_env="$current_root/.env"
elif [ "$primary_root" != "$current_root" ] && [ -f "$primary_root/.env" ]; then
  base_env="$primary_root/.env"
fi

set -a
# shellcheck disable=SC1090
. "$base_env"
set +a

postgres_db="${POSTGRES_DB:-momo}"
postgres_user="${POSTGRES_USER:-momo}"
postgres_password="${POSTGRES_PASSWORD:-change-me-postgres}"

tmp_env=".conductor/local.env.tmp"
cat > "$tmp_env" <<EOF
# Generated by .conductor/setup.sh. Do not commit.
# Worktree: $safe_name
COMPOSE_PROJECT_NAME=$compose_project
PORT=$api_port
CENT_PORT=$cent_port
POSTGRES_PORT=$postgres_port
HERMES_PORT=$hermes_port
DATABASE_URL=postgres://$postgres_user:$postgres_password@localhost:$postgres_port/$postgres_db
CENT_API_URL=http://localhost:$cent_port/api
EOF

case "${HERMES_BASE_URL:-}" in
  ""|http://localhost:*|http://127.0.0.1:*)
    printf 'HERMES_BASE_URL=http://localhost:%s/v1\n' "$hermes_port" >> "$tmp_env"
    ;;
esac

mv "$tmp_env" .conductor/local.env
ln -sfn .conductor/local.env .env.worktree

echo "wrote .conductor/local.env"
echo "linked .env.worktree -> .conductor/local.env"
echo "compose project: $compose_project"
echo "ports: api=$api_port centrifugo=$cent_port postgres=$postgres_port hermes=$hermes_port"

if [ -f .conductor/setup.local.sh ]; then
  bash .conductor/setup.local.sh
fi

echo "momo worktree ready"
