[package]
name = "momo-wire"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true
sha2.workspace = true
base64.workspace = true
hex.workspace = true
thiserror.workspace = true
