/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email/password and receive a session token pair. */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token into a new access/refresh pair.
         * @description Single-use rotation (MOMO-300): the presented refresh token is revoked atomically; replaying it returns 401. Exactly one concurrent caller wins.
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the presented session tokens (idempotent).
         * @description Requires a signature-valid access token in the Authorization header (an already-revoked access token still gets a 200 — logging out twice is idempotent, reported via `alreadyRevoked`). The optional body may carry the session's refresh token so the whole session dies at once; a refresh token belonging to another member/workspace is rejected with 403.
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/realtime-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a short-lived Centrifugo connection JWT.
         * @description The returned token authenticates the WebSocket connection at the server-owned `realtimeWebSocketUrl` (ADR-0110). Requires the `messages:read` scope for humans.
         */
        post: operations["authRealtimeToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join a workspace with an invite code (public, no auth).
         * @description Redeems a high-entropy invite code, creating (201) or reusing (200) a human member, granting membership in every joinable public channel, and issuing a session token pair. Snake-case body aliases accepted by the server: `display_name`, `time_zone`/`tz`.
         */
        post: operations["publicJoin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active workspace members (humans and agents). */
        get: operations["getRoster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compatibility alias of the roster endpoint.
         * @description Same handler, parameters, and response as `/roster`.
         */
        get: operations["getRosterMembersAlias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List channels the authenticated member belongs to.
         * @description Returns public/private/dm channels where the caller has an active membership, ordered public -> private -> dm, then by name.
         */
        get: operations["listChannels"];
        put?: never;
        /** Create a public/private channel (workspace admin only). */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/channels/{channelId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read message history (seq-cursor pagination).
         * @description Without cursors, returns the newest messages ordered by `seq` descending. `before=<seq>` pages older history (descending). `after=<seq>` is the realtime-recovery backfill: it returns messages with `seq > after` in ASCENDING order and takes precedence over `before` when both are present.
         */
        get: operations["getMessageHistory"];
        put?: never;
        /**
         * Send a message (idempotent via clientMsgId).
         * @description The single write path (L4 §3.1): one transaction bumps the gapless per-channel `seq`, inserts the message, and enqueues the realtime broadcast through the transactional outbox. Retrying with the same `clientMsgId` returns the original message (exactly-once effect) — the response status is 201 in both cases.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/read-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bulk read-state for every channel the member belongs to.
         * @description ADR-0109 read surface. One entry per active membership on a non-archived channel, bound to the authenticated principal.
         */
        get: operations["listReadStates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/channels/{channelId}/read-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Advance the caller's read cursor for a channel.
         * @description Monotonic: the effective cursor is `max(current, min(requested, latestSeq))` — it never moves backward and never beyond the channel head. The cursor owner is always the authenticated principal; no member id is accepted in the body.
         */
        put: operations["updateReadState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/dms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's active 1:1 DM channels.
         * @description Newest-created first; at most 500 channels.
         */
        get: operations["listDms"];
        put?: never;
        /**
         * Open (or reuse) the 1:1 DM channel with another member.
         * @description Idempotent per participant pair: creates the DM channel on first call (201) and returns the existing one afterwards (200). Snake-case body alias accepted by the server, `member_id`.
         */
        post: operations["openDm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List approval projections visible to the caller.
         * @description Requires an active human member; only approvals on channels where the caller has an active membership are returned. Ordered by expiry (soonest first, NULLs last), then newest first.
         */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/approvals/{approvalId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or reject a pending approval (idempotent).
         * @description Human-only. `client_decision_id` provides idempotency — retrying the same decision returns the original receipt (200); a different decision under the same `client_decision_id` returns a 409 receipt with status `idempotency_conflict`. Expected failures (403/404/409) return the SAME receipt schema (not the generic error envelope) with a diagnostic `status`; the generic error envelope is used only for 400 body/path mismatches and 401 auth failures.
         */
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Generic error envelope. Some errors (no message) may return an empty body with only the status code. */
        ErrorResponse: {
            error: {
                message: string;
            };
        };
        LoginRequest: {
            /** @description Human member email within the workspace. */
            email: string;
            password: string;
            /**
             * Format: uuid
             * @description Optional explicit workspace UUID. When omitted (or not a valid UUID) the server falls back to the seeded demo workspace (single-tenant v0 convenience).
             */
            workspace?: string;
            /** @description Optional platform-admin elevation secret (snake-case alias `platform_admin_secret`). Irrelevant to the web v0 client; the account password must still verify before it can add scope. */
            platformAdminSecret?: string;
        };
        LoginResponse: {
            /** @description Bearer access JWT, 15 minute TTL. */
            accessToken: string;
            /** @description Single-use rotating refresh JWT, 30 day TTL. */
            refreshToken: string;
            member: components["schemas"]["Member"];
            /** @description The ONLY authority for the realtime WebSocket address (ADR-0110). Never derive it from the API origin. */
            realtimeWebSocketUrl: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RefreshResponse: {
            accessToken: string;
            refreshToken: string;
        };
        LogoutRequest: {
            /** @description Optional refresh token of the same session to revoke alongside the access token. */
            refreshToken?: string;
        };
        LogoutResponse: {
            /** @enum {string} */
            status: "ok";
            /** @description The access token transitioned to revoked in this call. */
            revokedAccess: boolean;
            /** @description The body refresh token transitioned to revoked in this call. */
            revokedRefresh: boolean;
            /** @description Nothing new was revoked (idempotent repeat logout). */
            alreadyRevoked: boolean;
        };
        RealtimeTokenResponse: {
            /** @description Centrifugo connection JWT. */
            token: string;
            /** @enum {string} */
            tokenType: "centrifugo.connection.jwt";
            /** Format: int64 */
            expiresAtMs: number;
            ttlSeconds: number;
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            memberId: string;
        };
        /** @description Minimal member identity as returned by login/join. */
        Member: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** @enum {string} */
            kind: "human" | "agent";
            displayName: string;
            handle: string;
        };
        JoinRequest: {
            /** @description Raw invite code (shown once at creation; server stores only the hash). */
            code: string;
            /** @description Lowercased/trimmed server-side; must contain `@`. */
            email: string;
            /** @description 1..100 chars after trimming. Snake-case alias `display_name`. */
            displayName: string;
            /** @description Optional; derived from the email local part when omitted. */
            handle?: string;
            /** @description Required, at most 1024 chars. */
            password: string;
            /** @description Optional IANA time zone; defaults to UTC. Aliases `time_zone`, `tz`. */
            timeZone?: string;
        };
        JoinMembership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            channelId: string;
            role: components["schemas"]["MembershipRole"];
        };
        /** @description Invite metadata. The raw code is intentionally absent (only returned once at creation, outside this surface). */
        InviteCode: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** @description Safe display hint (may be empty). */
            codePreview: string;
            role: components["schemas"]["MembershipRole"];
            maxUses: number;
            usedCount: number;
            /** Format: int64 */
            expiresAtMs: number;
            /** Format: int64 */
            revokedAtMs?: number;
            /** Format: uuid */
            revokedBy?: string;
            revocationReason?: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: int64 */
            createdAtMs: number;
            /** Format: int64 */
            updatedAtMs: number;
        };
        JoinResponse: {
            accessToken: string;
            refreshToken: string;
            /** Format: uuid */
            workspaceId: string;
            member: components["schemas"]["Member"];
            /** @description Server-owned WebSocket address authority (ADR-0110). */
            realtimeWebSocketUrl: string;
            /** @description Public-channel memberships granted by this join. */
            memberships: components["schemas"]["JoinMembership"][];
            invite: components["schemas"]["InviteCode"];
            /** Format: uuid */
            redemptionId: string;
            /** @description True when a new member row was created (response status 201). */
            createdMember: boolean;
        };
        /** @description Roster entry. Human-only fields (email/timeZone) and agent-only fields (agentModel/ownerHumanId/maxConcurrentRuns/maxRunSteps) are present only for the matching kind; agent secrets and execution config are never exposed. */
        RosterMember: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** @enum {string} */
            kind: "human" | "agent";
            /** @enum {string} */
            status: "active" | "invited" | "suspended" | "deleted";
            displayName: string;
            handle: string;
            avatarUrl?: string;
            role?: components["schemas"]["MembershipRole"];
            channelCount: number;
            channelIds: string[];
            /** @description Public capability projection for agents; empty for humans. */
            capabilities: string[];
            email?: string;
            timeZone?: string;
            agentModel?: string;
            /** Format: uuid */
            ownerHumanId?: string;
            maxConcurrentRuns?: number;
            maxRunSteps?: number;
            /** Format: int64 */
            createdAtMs: number;
            /** Format: int64 */
            updatedAtMs: number;
        };
        WorkspaceRosterResponse: {
            members: components["schemas"]["RosterMember"][];
            humanCount: number;
            agentCount: number;
        };
        Channel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** @enum {string} */
            kind: "public" | "private" | "dm";
            /** @description Absent for DM channels. */
            name?: string;
            topic?: string;
            /** @description Canonical participant-pair hash; DM channels only. */
            dmKey?: string;
            /** @description Active participants for DM channels; empty array for public/private. */
            memberIds?: string[];
            /** Format: uuid */
            createdBy?: string;
            /**
             * Format: int64
             * @description Present only when the channel is archived.
             */
            archivedAtMs?: number;
        };
        WorkspaceChannelsResponse: {
            channels: components["schemas"]["Channel"][];
        };
        CreateChannelRequest: {
            /** @enum {string} */
            kind: "public" | "private";
            /** @description 1..80 chars; lowercased server-side. */
            name: string;
            /** @description At most 280 chars; blank collapses to absent. */
            topic?: string;
        };
        ChannelMembership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            channelId: string;
            /** Format: uuid */
            memberId: string;
            role: components["schemas"]["MembershipRole"];
            /** Format: int64 */
            joinedAtMs: number;
            /**
             * Format: int64
             * @description Present only after the member left the channel.
             */
            leftAtMs?: number;
        };
        CreateChannelResponse: {
            channel: components["schemas"]["Channel"];
            creatorMembership: components["schemas"]["ChannelMembership"];
        };
        /** @enum {string} */
        MembershipRole: "owner" | "admin" | "member" | "guest";
        SendMessageRequest: {
            /**
             * Format: uuid
             * @description Client-generated idempotency key (L4 §3.1).
             */
            clientMsgId: string;
            /**
             * @default text
             * @enum {string}
             */
            type: "text" | "tool_call" | "tool_result" | "diff" | "artifact" | "approval_request" | "system";
            body?: string;
            /** @description Simplified structured payload for v0 — a flat string-to-string map on send. The server-owned `mention_member_ids` key is stripped and recomputed server-side. */
            props?: {
                [key: string]: string;
            };
            /**
             * Format: uuid
             * @description Agent-run binding; agent principals only.
             */
            runId?: string;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            channelId: string;
            /**
             * Format: int64
             * @description Gapless per-channel sequence; the ordering authority.
             */
            seq: number;
            /** Format: int64 */
            hlcTs: number;
            hlcCount: number;
            /** Format: uuid */
            authorMemberId: string;
            /** @enum {string} */
            type: "text" | "tool_call" | "tool_result" | "diff" | "artifact" | "approval_request" | "system";
            body?: string;
            /** @description Arbitrary JSON object; includes the server-computed `mention_member_ids` array when the message mentions members. Omitted when empty. */
            props?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            runId?: string;
            /** Format: uuid */
            clientMsgId?: string;
            /** Format: int64 */
            createdAtMs: number;
        };
        MessagePage: {
            /** @description Descending by seq for head/`before` reads; ASCENDING for `after` backfill reads. */
            messages: components["schemas"]["Message"][];
            /**
             * Format: int64
             * @description Smallest seq in this page — pass as `before` to fetch older messages. Omitted when the page is empty.
             */
            nextBefore?: number;
        };
        UpdateReadStateRequest: {
            /** Format: int64 */
            last_read_seq: number;
        };
        ReadState: {
            /** Format: uuid */
            channel_id: string;
            /** Format: int64 */
            last_read_seq: number;
            /** Format: int64 */
            latest_seq: number;
            /** Format: int64 */
            unread_count: number;
            mention_count: number;
        };
        ReadStateListResponse: {
            read_states: components["schemas"]["ReadState"][];
        };
        OpenDirectMessageRequest: {
            /**
             * Format: uuid
             * @description The other participant (must differ from the caller). Snake-case alias accepted by the server, `member_id`.
             */
            memberId: string;
        };
        OpenDirectMessageResponse: {
            channel: components["schemas"]["Channel"];
            /** @description True when the DM channel was created by this call (status 201). */
            created: boolean;
        };
        ApprovalProjection: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workspace_id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            channel_id: string;
            /**
             * Format: uuid
             * @description The approval_request message, when one exists.
             */
            request_message_id?: string;
            /**
             * Format: uuid
             * @description The requesting agent member.
             */
            requested_by: string;
            /** @description Delegation subject, projected from `payload.on_behalf_of`. */
            on_behalf_of?: string;
            /** @description e.g. `tool_call`, `deploy`, `spend`. */
            action_type: string;
            payload: unknown;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "expired" | "cancelled";
            /**
             * Format: int64
             * @description Projected from payload when present as a number or numeric string.
             */
            estimated_micro_usd?: number;
            is_reversible?: boolean;
            /** Format: uuid */
            decided_by?: string;
            /** Format: int64 */
            decided_at_ms?: number;
            decision_reason?: string;
            /** Format: int64 */
            expires_at_ms?: number;
        };
        ApprovalProjectionPage: {
            approvals: components["schemas"]["ApprovalProjection"][];
        };
        ApprovalDecisionRequest: {
            /**
             * Format: uuid
             * @description Must equal the path approvalId.
             */
            approval_id: string;
            approve: boolean;
            /** @description Optional; trimmed and truncated to 2000 chars server-side. */
            reason?: string;
            /**
             * Format: uuid
             * @description Client-generated idempotency key for the decision.
             */
            client_decision_id: string;
        };
        /** @description Decision acknowledgement. Committed decisions carry status approved/rejected; expected failures reuse this shape with a diagnostic status (e.g. idempotency_conflict, forbidden, not_found, bad_request, expired, or the approval's current status on a 409). */
        ApprovalDecisionReceipt: {
            /** Format: uuid */
            approval_id: string;
            status: string;
            /**
             * Format: uuid
             * @description Absent for system-side outcomes such as expiry.
             */
            decided_by?: string;
            /** Format: int64 */
            decided_at_ms?: number;
            decision_reason?: string;
        };
    };
    responses: {
        /** @description Missing, invalid, expired, or revoked access token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not an active workspace member, or workspace scope mismatch. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Per-IP or per-member sliding-window rate limit exceeded (MOMO-300). Carries a `Retry-After` header in seconds. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
        WorkspaceId: string;
        /** @description Channel UUID. */
        ChannelId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Credentials verified; session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New token pair issued; the old refresh token is dead. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Invalid, expired, revoked, or already-used refresh token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Member is no longer active in this workspace. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Revocation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Missing/invalid access token signature. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Body refresh token does not match this session. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    authRealtimeToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeTokenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Missing scope or member no longer active. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    publicJoin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Existing member (same email) re-joined. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResponse"];
                };
            };
            /** @description New member created and joined. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResponse"];
                };
            };
            /** @description Invalid code/email/displayName/handle/password shape. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Role escalation or non-joinable member state. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invite code is invalid. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Already redeemed, exhausted, or no joinable channels. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invite code expired or revoked. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getRoster: {
        parameters: {
            query?: {
                /** @description Filter by member kind. Alias accepted by the server, `member_kind`. */
                kind?: "human" | "agent";
                /** @description Page size, clamped to 1..500. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roster of active members with an active channel membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRosterResponse"];
                };
            };
            /** @description kind must be human or agent. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getRosterMembersAlias: {
        parameters: {
            query?: {
                kind?: "human" | "agent";
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roster of active members with an active channel membership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRosterResponse"];
                };
            };
            /** @description kind must be human or agent. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listChannels: {
        parameters: {
            query?: {
                /** @description Include archived channels when `true`. CamelCase alias accepted by the server, `includeArchived`. */
                include_archived?: boolean;
                /** @description Page size, clamped to 1..500. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channels visible to the member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceChannelsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChannelRequest"];
            };
        };
        responses: {
            /** @description Channel created with the creator as channel owner. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateChannelResponse"];
                };
            };
            /** @description Invalid kind/name/topic shape. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not a workspace owner/admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Channel name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getMessageHistory: {
        parameters: {
            query?: {
                /** @description Page size, clamped to 1..200. */
                limit?: number;
                /** @description Return messages with `seq` strictly below this cursor (older). */
                before?: number;
                /** @description Return messages with `seq` strictly above this cursor (backfill, ascending). */
                after?: number;
            };
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
                /** @description Channel UUID. */
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Invalid workspace/channel id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not a member of this channel, or workspace scope mismatch. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
                /** @description Channel UUID. */
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Message committed with its authoritative `seq`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Invalid workspace/channel id. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not a member of this channel, or workspace scope mismatch. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Channel not found or not provisioned. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listReadStates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-state projections for the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadStateListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    updateReadState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
                /** @description Channel UUID. */
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReadStateRequest"];
            };
        };
        responses: {
            /** @description Effective read-state after the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadState"];
                };
            };
            /** @description last_read_seq must be non-negative, or invalid ids. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not a member of this channel, or workspace scope mismatch. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listDms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DM channels with active participant ids. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceChannelsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    openDm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenDirectMessageRequest"];
            };
        };
        responses: {
            /** @description Existing DM channel returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenDirectMessageResponse"];
                };
            };
            /** @description DM channel newly created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenDirectMessageResponse"];
                };
            };
            /** @description Target must be another member / invalid ids. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Active workspace member not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                /** @description Approval status filter; defaults to `pending`. */
                status?: "pending" | "approved" | "rejected" | "expired" | "cancelled";
                /** @description Page size, clamped to 1..500. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval projections. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalProjectionPage"];
                };
            };
            /** @description Invalid status filter. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not an active human workspace member. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace UUID. Must equal the workspace bound into the access token; any other value is rejected with 403 (tenant isolation, L4 §1.3). */
                workspaceId: components["parameters"]["WorkspaceId"];
                /** @description Approval UUID; must match the body `approval_id`. */
                approvalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Decision committed (or identical idempotent retry). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionReceipt"];
                };
            };
            /** @description approval_id does not match path / invalid ids. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Receipt-shaped expected failure (not human / not a channel member). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionReceipt"];
                };
            };
            /** @description Receipt-shaped expected failure (approval not found). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionReceipt"];
                };
            };
            /** @description Receipt-shaped expected failure — already decided, expired before decision, or idempotency conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionReceipt"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
}
