//! `invite_code` — create, list, revoke, regenerate, redeem (migration 003).
//!
//! Port of Swift `Routes/InviteRoutes.swift`. Create/list are the two the web
//! settings panel calls (`clients/web/src/features/settings/api.ts:442,449`).
//! Revoke/regenerate/redeem close the leak-response gap #1769 ports.
//!
//! **The raw code never exists in Rust except on the response boundary.** It is
//! generated by `momo_generate_invite_code()` and hashed by
//! `momo_invite_code_hash()` **inside the same statement**, so the plaintext code
//! travels exactly one way — out to the operator who just created it — and the
//! only durable record is a sha256. That is why creation (and regenerate) is one
//! CTE rather than generate-then-insert: two statements would put the code in an
//! application variable, and a code in a variable is a code in a log.

use momo_db::DbError;
use sqlx::PgConnection;
use uuid::Uuid;

/// The projected `invite_code` row. Field names match the client's `InviteCode`
/// interface (`features/settings/api.ts:413-428`) once serialized.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InviteCode {
    pub id: Uuid,
    pub workspace_id: Uuid,
    /// Last 6 characters of the code — a display hint, never the code.
    pub code_preview: String,
    pub role: String,
    pub max_uses: i32,
    pub used_count: i32,
    pub expires_at_ms: i64,
    pub revoked_at_ms: Option<i64>,
    pub revoked_by: Option<Uuid>,
    pub revocation_reason: Option<String>,
    pub created_by: Uuid,
    pub created_at_ms: i64,
    pub updated_at_ms: i64,
}

/// The one response that ever carries the raw code.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreatedInvite {
    pub invite: InviteCode,
    pub code: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum InviteSpecInvalid {
    #[error("invite role must be admin, member, or guest")]
    Role,
    #[error("maxUses must be between 1 and 10000")]
    MaxUses,
    #[error("expiresAtMs must be in the future")]
    ExpiresAtMs,
}

/// Swift `normalizedRole` (:465-473). `owner` is absent by design and migration
/// 003 refuses it at the column too (`invite_code_role_ck`): an invite link is a
/// self-service path, and no self-service path may mint an owner.
pub fn normalized_invite_role(role: Option<&str>) -> Result<&'static str, InviteSpecInvalid> {
    let value = role.unwrap_or("member").trim().to_ascii_lowercase();
    match value.as_str() {
        "admin" => Ok("admin"),
        "member" => Ok("member"),
        "guest" => Ok("guest"),
        _ => Err(InviteSpecInvalid::Role),
    }
}

/// Swift `validatedMaxUses` (:475-481). Absent means 1 — a single-use link is the
/// safe default for a credential someone will paste into a chat.
pub fn validated_max_uses(max_uses: Option<i32>) -> Result<i32, InviteSpecInvalid> {
    let value = max_uses.unwrap_or(1);
    if (1..=10_000).contains(&value) {
        Ok(value)
    } else {
        Err(InviteSpecInvalid::MaxUses)
    }
}

/// Swift `validatedExpiresAtMs` (:483-490). `None` lets the SQL default apply
/// (`now() + interval '7 days'`); a past instant is refused rather than stored as
/// an invite that is dead on arrival.
pub fn validated_expires_at_ms(
    expires_at_ms: Option<i64>,
    now_ms: i64,
) -> Result<Option<i64>, InviteSpecInvalid> {
    match expires_at_ms {
        None => Ok(None),
        Some(value) if value > now_ms => Ok(Some(value)),
        Some(_) => Err(InviteSpecInvalid::ExpiresAtMs),
    }
}

/// Swift `list`'s clamp (:122): default 50, floor 1, ceiling 200. A parse failure
/// resolves to the default rather than a 400 — the client sends `?limit=20` and
/// a stray value must not blank the panel.
pub fn clamp_invite_list_limit(raw: Option<&str>) -> i64 {
    raw.and_then(|value| value.parse::<i64>().ok())
        .unwrap_or(50)
        .clamp(1, 200)
}

const PROJECTION: &str = "SELECT i.id, \
                                 i.workspace_id, \
                                 i.code_preview, \
                                 i.role::text, \
                                 i.max_uses, \
                                 i.used_count, \
                                 floor(extract(epoch from i.expires_at) * 1000)::bigint, \
                                 CASE WHEN i.revoked_at IS NULL THEN NULL \
                                      ELSE floor(extract(epoch from i.revoked_at) * 1000)::bigint \
                                 END, \
                                 i.revoked_by, \
                                 i.revocation_reason, \
                                 i.created_by, \
                                 floor(extract(epoch from i.created_at) * 1000)::bigint, \
                                 floor(extract(epoch from i.updated_at) * 1000)::bigint";

type InviteRow = (
    Uuid,
    Uuid,
    String,
    String,
    i32,
    i32,
    i64,
    Option<i64>,
    Option<Uuid>,
    Option<String>,
    Uuid,
    i64,
    i64,
);

/// The same projection with a trailing id (redemption) or raw code (create).
type CreatedInviteRow = (
    Uuid,
    Uuid,
    String,
    String,
    i32,
    i32,
    i64,
    Option<i64>,
    Option<Uuid>,
    Option<String>,
    Uuid,
    i64,
    i64,
    String,
);

type RedeemedInviteRow = (
    Uuid,
    Uuid,
    String,
    String,
    i32,
    i32,
    i64,
    Option<i64>,
    Option<Uuid>,
    Option<String>,
    Uuid,
    i64,
    i64,
    Uuid,
);

fn invite_from_row(row: InviteRow) -> InviteCode {
    InviteCode {
        id: row.0,
        workspace_id: row.1,
        code_preview: row.2,
        role: row.3,
        max_uses: row.4,
        used_count: row.5,
        expires_at_ms: row.6,
        revoked_at_ms: row.7,
        revoked_by: row.8,
        revocation_reason: row.9,
        created_by: row.10,
        created_at_ms: row.11,
        updated_at_ms: row.12,
    }
}

/// Create one invite and return it **with** its raw code (Swift :43-90).
///
/// `expires_at_ms` of `None` falls through to the column default via `COALESCE`,
/// exactly as Swift does, so "no expiry supplied" and "seven days" stay one
/// decision made in one place (the migration).
pub async fn create_invite(
    conn: &mut PgConnection,
    workspace_id: Uuid,
    role: &str,
    max_uses: i32,
    expires_at_ms: Option<i64>,
    created_by: Uuid,
) -> Result<CreatedInvite, DbError> {
    let row: CreatedInviteRow = sqlx::query_as(&format!(
        "WITH generated AS ( \
           SELECT momo_generate_invite_code() AS raw_code \
         ), \
         inserted AS ( \
           INSERT INTO invite_code \
             (workspace_id, code_hash, code_preview, role, max_uses, \
              expires_at, created_by, metadata) \
           SELECT $1, \
                  momo_invite_code_hash(raw_code), \
                  right(raw_code, 6), \
                  $2::membership_role, \
                  $3, \
                  COALESCE(to_timestamp($4 / 1000.0), now() + interval '7 days'), \
                  $5, \
                  '{{}}'::jsonb \
             FROM generated \
           RETURNING * \
         ) \
         {PROJECTION}, g.raw_code \
           FROM inserted i \
           CROSS JOIN generated g"
    ))
    .bind(workspace_id)
    .bind(role)
    .bind(max_uses)
    .bind(expires_at_ms)
    .bind(created_by)
    .fetch_one(&mut *conn)
    .await?;

    let code = row.13.clone();
    Ok(CreatedInvite {
        invite: invite_from_row((
            row.0, row.1, row.2, row.3, row.4, row.5, row.6, row.7, row.8, row.9, row.10, row.11,
            row.12,
        )),
        code,
    })
}

/// Read one invite by id (Swift `JoinRoutes.loadInviteDTO` :685-720).
///
/// Added for B4.3: the join response carries the invite it just spent, and the
/// read has to happen **after** the usage increment so `usedCount` is the value
/// that join produced. It shares [`PROJECTION`] with [`list_invites`] rather than
/// spelling the columns again — the response the settings panel decodes and the
/// one the join answers with are the same object, and one projection is what
/// keeps them that way.
pub async fn read_invite(
    conn: &mut PgConnection,
    invite_id: Uuid,
) -> Result<Option<InviteCode>, DbError> {
    let row: Option<InviteRow> = sqlx::query_as(&format!(
        "{PROJECTION} \
           FROM invite_code i \
          WHERE i.id = $1"
    ))
    .bind(invite_id)
    .fetch_optional(&mut *conn)
    .await?;
    Ok(row.map(invite_from_row))
}

/// List invites newest-first (Swift :128-155).
///
/// The workspace is not in the `WHERE` clause and does not need to be: the RLS
/// policy on `invite_code` is `workspace_id = current_setting('app.workspace_id')`,
/// so the tenant transaction already scoped the read. Adding the predicate would
/// suggest the isolation lives here, and it does not.
pub async fn list_invites(
    conn: &mut PgConnection,
    include_revoked: bool,
    limit: i64,
) -> Result<Vec<InviteCode>, DbError> {
    let rows: Vec<InviteRow> = sqlx::query_as(&format!(
        "{PROJECTION} \
           FROM invite_code i \
          WHERE ($1 OR i.revoked_at IS NULL) \
          ORDER BY i.created_at DESC \
          LIMIT $2"
    ))
    .bind(include_revoked)
    .bind(limit)
    .fetch_all(&mut *conn)
    .await?;
    Ok(rows.into_iter().map(invite_from_row).collect())
}

/// One successful spend of an invite, projected for the operator status read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InviteRedemption {
    pub id: Uuid,
    pub member_id: Uuid,
    pub email: Option<String>,
    pub redeemed_at_ms: i64,
}

/// Revoke / regenerate refusals that are a client-visible state, not a DB fault.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum InviteMutationInvalid {
    #[error("invite code not found")]
    NotFound,
    #[error("invite code not found or already revoked")]
    NotFoundOrRevoked,
    #[error("invite code is already consumed")]
    AlreadyConsumed,
}

/// Member-self redeem refusals (Swift `redeem` :425-429 / :360).
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum InviteRedeemInvalid {
    #[error("invite code is invalid, expired, exhausted, revoked, or already redeemed")]
    Unusable,
    #[error("not a workspace member")]
    NotMember,
    #[error("member is banned from this workspace")]
    Banned,
}

/// Outcome of [`revoke_invite`]. `newly_revoked` is Swift's `newly_revoked`
/// column (:192): only the first flip writes `invite.revoked`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RevokedInvite {
    pub invite: InviteCode,
    pub newly_revoked: bool,
}

/// Outcome of [`redeem_invite_for_member`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RedeemedInvite {
    pub invite: InviteCode,
    pub redemption_id: Uuid,
}

/// Trim Swift `RevokeInviteRequest.reason` (:170). Empty after trim is absence.
pub fn normalized_revoke_reason(reason: Option<&str>) -> Option<String> {
    reason
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
}

/// Redemptions of one invite, oldest first. The workspace is the RLS GUC, same
/// as [`list_invites`].
pub async fn list_invite_redemptions(
    conn: &mut PgConnection,
    invite_id: Uuid,
) -> Result<Vec<InviteRedemption>, DbError> {
    let rows: Vec<(Uuid, Uuid, Option<String>, i64)> = sqlx::query_as(
        "SELECT r.id, \
                r.member_id, \
                r.email, \
                floor(extract(epoch from r.redeemed_at) * 1000)::bigint \
           FROM invite_code_redemption r \
          WHERE r.invite_code_id = $1 \
          ORDER BY r.redeemed_at ASC, r.id ASC",
    )
    .bind(invite_id)
    .fetch_all(&mut *conn)
    .await?;
    Ok(rows
        .into_iter()
        .map(|(id, member_id, email, redeemed_at_ms)| InviteRedemption {
            id,
            member_id,
            email,
            redeemed_at_ms,
        })
        .collect())
}

/// Revoke one invite (Swift :176-215).
///
/// Ticket #1769 tightens Swift on one point: an **exhausted** invite
/// (`used_count >= max_uses`) is 409 rather than a no-op mark. Remaining uses
/// can still be cancelled. Already-revoked stays Swift-idempotent (200, no
/// second audit).
pub async fn revoke_invite(
    conn: &mut PgConnection,
    invite_id: Uuid,
    revoked_by: Uuid,
    reason: Option<&str>,
) -> Result<Result<RevokedInvite, InviteMutationInvalid>, DbError> {
    let locked: Option<(Option<chrono::DateTime<chrono::Utc>>, i32, i32)> = sqlx::query_as(
        "SELECT revoked_at, used_count, max_uses \
           FROM invite_code \
          WHERE id = $1 \
          FOR UPDATE",
    )
    .bind(invite_id)
    .fetch_optional(&mut *conn)
    .await?;
    let Some((revoked_at, used_count, max_uses)) = locked else {
        return Ok(Err(InviteMutationInvalid::NotFound));
    };
    if revoked_at.is_none() && used_count >= max_uses {
        return Ok(Err(InviteMutationInvalid::AlreadyConsumed));
    }

    let row: InviteRow = sqlx::query_as(&format!(
        "UPDATE invite_code \
            SET revoked_at = COALESCE(revoked_at, now()), \
                revoked_by = COALESCE(revoked_by, $2), \
                revocation_reason = COALESCE(revocation_reason, $3), \
                updated_at = now() \
          WHERE id = $1 \
        RETURNING {PROJECTION_COLUMNS}"
    ))
    .bind(invite_id)
    .bind(revoked_by)
    .bind(reason)
    .fetch_one(&mut *conn)
    .await?;

    Ok(Ok(RevokedInvite {
        invite: invite_from_row(row),
        newly_revoked: revoked_at.is_none(),
    }))
}

/// Atomically revoke the old row and mint a replacement (Swift :251-309).
///
/// Role, `max_uses`, and `metadata` are copied. Expiry resets to seven days,
/// matching Swift (`now() + interval '7 days'`), not the leftover TTL.
pub async fn regenerate_invite(
    conn: &mut PgConnection,
    invite_id: Uuid,
    created_by: Uuid,
) -> Result<Result<CreatedInvite, InviteMutationInvalid>, DbError> {
    let row: Option<CreatedInviteRow> = sqlx::query_as(&format!(
        "WITH locked AS ( \
           SELECT * \
             FROM invite_code \
            WHERE id = $1 \
              AND revoked_at IS NULL \
            FOR UPDATE \
         ), \
         revoked AS ( \
           UPDATE invite_code i \
              SET revoked_at = now(), \
                  revoked_by = $2, \
                  revocation_reason = 'regenerated', \
                  updated_at = now() \
             FROM locked l \
            WHERE i.id = l.id \
           RETURNING l.* \
         ), \
         generated AS ( \
           SELECT momo_generate_invite_code() AS raw_code \
         ), \
         inserted AS ( \
           INSERT INTO invite_code \
             (workspace_id, code_hash, code_preview, role, max_uses, \
              expires_at, created_by, metadata) \
           SELECT r.workspace_id, \
                  momo_invite_code_hash(g.raw_code), \
                  right(g.raw_code, 6), \
                  r.role, \
                  r.max_uses, \
                  now() + interval '7 days', \
                  $2, \
                  r.metadata \
             FROM revoked r \
             CROSS JOIN generated g \
           RETURNING * \
         ) \
         {PROJECTION}, g.raw_code \
           FROM inserted i \
           CROSS JOIN generated g"
    ))
    .bind(invite_id)
    .bind(created_by)
    .fetch_optional(&mut *conn)
    .await?;

    let Some(row) = row else {
        return Ok(Err(InviteMutationInvalid::NotFoundOrRevoked));
    };
    let code = row.13.clone();
    Ok(Ok(CreatedInvite {
        invite: invite_from_row((
            row.0, row.1, row.2, row.3, row.4, row.5, row.6, row.7, row.8, row.9, row.10, row.11,
            row.12,
        )),
        code,
    }))
}

/// Authenticated member spends a code for themselves (Swift :345-436).
///
/// Public join is [`crate::join::redeem_invite_in_tx`]. This path does not
/// create a member — the caller already is one — and answers Swift's single
/// 400 when the code cannot be spent.
pub async fn redeem_invite_for_member(
    conn: &mut PgConnection,
    workspace_id: Uuid,
    member_id: Uuid,
    code: &str,
    email: Option<&str>,
) -> Result<Result<RedeemedInvite, InviteRedeemInvalid>, DbError> {
    let identity: Option<(Option<String>, String)> = sqlx::query_as(
        "SELECT h.email, m.handle \
           FROM member m \
           LEFT JOIN human h \
             ON h.workspace_id = m.workspace_id AND h.member_id = m.id \
          WHERE m.workspace_id = $1 AND m.id = $2",
    )
    .bind(workspace_id)
    .bind(member_id)
    .fetch_optional(&mut *conn)
    .await?;
    let Some((stored_email, handle)) = identity else {
        return Ok(Err(InviteRedeemInvalid::NotMember));
    };
    let ban_email = stored_email.as_deref().or(email).unwrap_or("");
    if crate::join::is_identity_banned_in_tx(conn, ban_email, &handle).await? {
        return Ok(Err(InviteRedeemInvalid::Banned));
    }

    let row: Option<RedeemedInviteRow> = sqlx::query_as(&format!(
        "WITH matched AS ( \
           SELECT i.id \
             FROM invite_code i \
            WHERE i.code_hash = momo_invite_code_hash($3) \
              AND i.revoked_at IS NULL \
              AND i.expires_at > now() \
              AND i.used_count < i.max_uses \
              AND NOT EXISTS ( \
                SELECT 1 \
                  FROM invite_code_redemption r \
                 WHERE r.invite_code_id = i.id \
                   AND r.member_id = $2 \
              ) \
            FOR UPDATE \
         ), \
         updated AS ( \
           UPDATE invite_code i \
              SET used_count = i.used_count + 1, \
                  last_used_at = now(), \
                  updated_at = now() \
             FROM matched m \
            WHERE i.id = m.id \
           RETURNING i.* \
         ), \
         redemption AS ( \
           INSERT INTO invite_code_redemption \
             (workspace_id, invite_code_id, member_id, email) \
           SELECT $1, u.id, $2, $4 \
             FROM updated u \
           RETURNING id \
         ) \
         {PROJECTION}, r.id \
           FROM updated i \
           JOIN redemption r ON true"
    ))
    .bind(workspace_id)
    .bind(member_id)
    .bind(code)
    .bind(email)
    .fetch_optional(&mut *conn)
    .await?;

    let Some(row) = row else {
        return Ok(Err(InviteRedeemInvalid::Unusable));
    };
    Ok(Ok(RedeemedInvite {
        invite: invite_from_row((
            row.0, row.1, row.2, row.3, row.4, row.5, row.6, row.7, row.8, row.9, row.10, row.11,
            row.12,
        )),
        redemption_id: row.13,
    }))
}

/// Column list shared by the mutation `RETURNING` clauses. [`PROJECTION`]
/// already includes `SELECT`, so UPDATE … RETURNING cannot reuse it as-is.
const PROJECTION_COLUMNS: &str = "id, \
                                 workspace_id, \
                                 code_preview, \
                                 role::text, \
                                 max_uses, \
                                 used_count, \
                                 floor(extract(epoch from expires_at) * 1000)::bigint, \
                                 CASE WHEN revoked_at IS NULL THEN NULL \
                                      ELSE floor(extract(epoch from revoked_at) * 1000)::bigint \
                                 END, \
                                 revoked_by, \
                                 revocation_reason, \
                                 created_by, \
                                 floor(extract(epoch from created_at) * 1000)::bigint, \
                                 floor(extract(epoch from updated_at) * 1000)::bigint";

#[cfg(test)]
mod tests {
    use super::*;

    /// No self-service path may mint an owner — the API and migration 003's
    /// `invite_code_role_ck` agree, and this is the half that answers 400
    /// instead of 500.
    #[test]
    fn owner_is_not_an_invitable_role() {
        assert_eq!(normalized_invite_role(None).expect("default"), "member");
        assert_eq!(
            normalized_invite_role(Some(" ADMIN ")).expect("admin"),
            "admin"
        );
        assert_eq!(
            normalized_invite_role(Some("guest")).expect("guest"),
            "guest"
        );
        assert_eq!(
            normalized_invite_role(Some("owner")),
            Err(InviteSpecInvalid::Role)
        );
        assert_eq!(
            normalized_invite_role(Some("platform_admin")),
            Err(InviteSpecInvalid::Role)
        );
    }

    #[test]
    fn max_uses_defaults_to_one_and_is_bounded_by_the_column_check() {
        assert_eq!(validated_max_uses(None).expect("default"), 1);
        assert_eq!(validated_max_uses(Some(10_000)).expect("max"), 10_000);
        assert_eq!(validated_max_uses(Some(0)), Err(InviteSpecInvalid::MaxUses));
        assert_eq!(
            validated_max_uses(Some(10_001)),
            Err(InviteSpecInvalid::MaxUses)
        );
        assert_eq!(
            validated_max_uses(Some(-5)),
            Err(InviteSpecInvalid::MaxUses)
        );
    }

    #[test]
    fn an_expiry_in_the_past_is_refused_rather_than_stored_dead() {
        let now = 1_700_000_000_000;
        assert_eq!(validated_expires_at_ms(None, now), Ok(None));
        assert_eq!(
            validated_expires_at_ms(Some(now + 1), now),
            Ok(Some(now + 1))
        );
        assert_eq!(
            validated_expires_at_ms(Some(now), now),
            Err(InviteSpecInvalid::ExpiresAtMs),
            "migration 003 requires expires_at > created_at; equality is not future"
        );
    }

    #[test]
    fn the_list_limit_clamps_instead_of_rejecting() {
        assert_eq!(clamp_invite_list_limit(None), 50);
        assert_eq!(clamp_invite_list_limit(Some("20")), 20);
        assert_eq!(clamp_invite_list_limit(Some("0")), 1);
        assert_eq!(clamp_invite_list_limit(Some("9999")), 200);
        assert_eq!(
            clamp_invite_list_limit(Some("twenty")),
            50,
            "a stray value must not blank the panel"
        );
    }

    #[test]
    fn revoke_reason_trims_to_absence() {
        assert_eq!(normalized_revoke_reason(None), None);
        assert_eq!(normalized_revoke_reason(Some("  ")), None);
        assert_eq!(
            normalized_revoke_reason(Some("  leaked  ")).as_deref(),
            Some("leaked")
        );
    }
}
