#!/usr/bin/env sh
# =============================================================================
# scripts/local_alpha_runner.sh — MOMO-240 local internal alpha runner
#
# Plan mode prints the exact local flow without starting anything.
# Execute mode starts a local Docker stack plus host-run Swift services, writes
# logs/evidence outside the repository by default, and prints the URLs/env/logs
# an alpha tester should inspect.
#
# No AWS/cloud resources are created. Secret env files must be absolute paths
# outside the repo. If no secret file is supplied in mock Hermes mode, the runner
# creates a dev-only env file in the evidence directory, also outside the repo.
# =============================================================================
set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd)

MODE=plan
HERMES_MODE=mock
SECRET_ENV_FILE=
EXTERNAL_SMOKE=0
TMP_BASE=${TMPDIR:-/tmp}
TMP_BASE=${TMP_BASE%/}
EVIDENCE_ROOT=${LOCAL_ALPHA_EVIDENCE_ROOT:-$TMP_BASE/momo-local-alpha}
KEEP_RUNNING=1
API_PROXY_HOST=${LOCAL_ALPHA_API_PROXY_HOST:-host.docker.internal}

usage() {
  cat <<'EOF'
Usage:
  scripts/local_alpha_runner.sh plan [options]
  scripts/local_alpha_runner.sh execute [options]

Modes:
  plan | --plan | --dry-run
      Print the flow, URLs, env source, and evidence layout. Does not start
      Docker or Swift processes.

  execute | --execute
      Start Docker PG18+Centrifugo, run migrations/RLS prep, start optional
      mock Hermes, start MomoServer/OutboxRelay/AgentWorker, run macOS smoke,
      and write evidence/logs.

Options:
  --hermes mock|external
      mock starts scripts/mock_hermes.py locally. external only verifies
      HERMES_BASE_URL/HERMES_API_KEY are set in --secret-env and does not probe
      the provider unless --external-smoke is also set.

  --external-smoke
      With --hermes external, delegate to scripts/verify_external_agent_provider.sh
      for the OpenAI-compatible SSE preflight plus one
      channel message -> agent run -> external runtime -> agent response
      roundtrip. Requires --secret-env outside the repo.

  --secret-env /absolute/path/outside/repo.env
      Secret env file to source. Must be outside this repository. Required for
      --hermes external. Optional for mock mode.

  --evidence-root /absolute/or/relative/path
      Root directory for evidence run folders. Defaults to
      ${TMPDIR:-/tmp}/momo-local-alpha.

  --stop-after-smoke
      Execute the flow, then stop host Swift/mock processes and Docker compose.
      Default execute behavior leaves the local alpha stack running and prints a
      stop command.

  --api-proxy-host host.docker.internal
      Hostname Centrifugo should use from inside Docker to call the host-run
      MomoServer subscribe proxy. Defaults to host.docker.internal.

Examples:
  scripts/local_alpha_runner.sh plan
  scripts/local_alpha_runner.sh execute --hermes mock
  scripts/local_alpha_runner.sh execute --hermes external --secret-env "$HOME/.momo/local-alpha.env"
  scripts/local_alpha_runner.sh execute --hermes external --external-smoke --secret-env "$HOME/.momo/external-agent.env"
EOF
}

fail() {
  echo "[local-alpha] ERROR: $*" >&2
  exit 1
}

abs_existing_file() {
  path=$1
  case "$path" in
    /*) ;;
    *) fail "path must be absolute: $path" ;;
  esac
  [ -f "$path" ] || fail "file not found: $path"
  dir=$(dirname -- "$path")
  base=$(basename -- "$path")
  dir_abs=$(CDPATH='' cd -- "$dir" && pwd -P)
  printf '%s/%s\n' "$dir_abs" "$base"
}

abs_dir_path() {
  path=$1
  case "$path" in
    /*) printf '%s\n' "$path" ;;
    *) printf '%s/%s\n' "$(pwd -P)" "$path" ;;
  esac
}

assert_secret_env_outside_repo() {
  file=$1
  case "$file" in
    "$REPO_ROOT"|"$REPO_ROOT"/*)
      fail "--secret-env must be outside the repo: $file"
      ;;
  esac
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "missing required command: $1"
  fi
}

redact_url() {
  printf '%s' "$1" | sed -E 's#//([^/:@]+):([^@]+)@#//***:***@#g'
}

print_redacted_env_value() {
  key=$1
  value=${2:-}
  case "$key" in
    *PASSWORD*|*KEY*|*HMAC*|*TOKEN*|*SECRET*)
      if [ "$value" = "" ]; then
        printf '<unset>'
      else
        printf '<set:redacted>'
      fi
      ;;
    *URL*)
      redact_url "$value"
      ;;
    *)
      printf '%s' "$value"
      ;;
  esac
}

write_generated_env() {
  ENV_FILE="$EVIDENCE_DIR/local-alpha.env"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/local_alpha_runner.sh outside the repository.
# Dev-only local alpha values. Do not copy into git.
COMPOSE_PROJECT_NAME=momo240_$$
POSTGRES_DB=momo
POSTGRES_USER=momo
POSTGRES_PASSWORD=momo240_local_postgres
POSTGRES_PORT=${POSTGRES_PORT:-25432}
DATABASE_URL=postgres://momo:momo240_local_postgres@localhost:${POSTGRES_PORT:-25432}/momo
CENT_PORT=${CENT_PORT:-28000}
CENT_TOKEN_HMAC=momo240-local-cent-token
CENT_API_KEY=momo240-local-cent-api-key
CENT_API_URL=http://localhost:${CENT_PORT:-28000}/api
JWT_HMAC=momo240-local-jwt
PORT=${PORT:-28080}
HOST=0.0.0.0
HERMES_PORT=${HERMES_PORT:-28088}
HERMES_BASE_URL=http://localhost:${HERMES_PORT:-28088}/v1
HERMES_API_KEY=momo240-local-hermes-key
WORKER_POLL_INTERVAL_MS=100
RELAY_POLL_INTERVAL_MS=100
EOF
}

load_env_file() {
  # shellcheck disable=SC1090
  set -a
  . "$ENV_FILE"
  set +a

  POSTGRES_DB=${POSTGRES_DB:-momo}
  POSTGRES_PORT=${POSTGRES_PORT:-5432}
  CENT_PORT=${CENT_PORT:-8000}
  PORT=${PORT:-8080}
  HOST=${HOST:-0.0.0.0}
  HERMES_PORT=${HERMES_PORT:-8088}
  DATABASE_URL=${DATABASE_URL:-postgres://${POSTGRES_USER:-momo}:${POSTGRES_PASSWORD:-momo}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}}
  CENT_API_URL=${CENT_API_URL:-http://localhost:${CENT_PORT}/api}
  case "$CENT_API_URL" in
    *centrifugo*) CENT_API_URL=http://localhost:${CENT_PORT}/api ;;
  esac
  HERMES_BASE_URL=${HERMES_BASE_URL:-http://localhost:${HERMES_PORT}/v1}
  HERMES_API_KEY=${HERMES_API_KEY:-}
  CENT_API_KEY=${CENT_API_KEY:-}
  CENT_TOKEN_HMAC=${CENT_TOKEN_HMAC:-}
  JWT_HMAC=${JWT_HMAC:-}

  export ENV_FILE POSTGRES_DB POSTGRES_PORT CENT_PORT PORT HOST HERMES_PORT
  export DATABASE_URL CENT_API_URL HERMES_BASE_URL HERMES_API_KEY
  export CENT_API_KEY CENT_TOKEN_HMAC JWT_HMAC
}

write_local_centrifugo_config() {
  CENTRIFUGO_CONFIG="$EVIDENCE_DIR/centrifugo.local-alpha.json"
  cat >"$CENTRIFUGO_CONFIG" <<EOF
{
  "channel": {
    "namespaces": [
      { "name": "ch", "presence": true, "join_leave": true, "force_push_join_leave": true,
        "history_size": 300, "history_ttl": "720h", "history_meta_ttl": "744h",
        "force_recovery": true, "force_positioning": true,
        "subscribe_proxy_enabled": true,
        "channel_regex": "^ws[0-9A-Fa-f-]{36}\\\\.[0-9A-Fa-f-]{36}$" },
      { "name": "dm", "presence": true, "history_size": 300, "history_ttl": "720h",
        "history_meta_ttl": "744h", "force_recovery": true,
        "allow_user_limited_channels": true },
      { "name": "agent", "presence": true, "join_leave": true, "force_push_join_leave": true,
        "history_size": 100, "history_ttl": "24h", "history_meta_ttl": "48h",
        "force_recovery": true },
      { "name": "user", "history_size": 50, "history_ttl": "168h",
        "history_meta_ttl": "192h", "force_recovery": true }
    ],
    "proxy": {
      "subscribe": { "endpoint": "http://${API_PROXY_HOST}:${PORT}/v1/centrifugo/subscribe" }
    }
  },
  "client": { "subscription_token": { "enabled": true } }
}
EOF

  COMPOSE_OVERRIDE="$EVIDENCE_DIR/docker-compose.local-alpha.yml"
  cat >"$COMPOSE_OVERRIDE" <<EOF
services:
  centrifugo:
    volumes:
      - ${CENTRIFUGO_CONFIG}:/centrifugo/centrifugo.json:ro
EOF
  export CENTRIFUGO_CONFIG COMPOSE_OVERRIDE
}

compose_cmd() {
  docker compose --env-file "$ENV_FILE" \
    -f "$REPO_ROOT/infra/docker-compose.yml" \
    -f "$COMPOSE_OVERRIDE" "$@"
}

log_command_line() {
  printf '$'
  for arg in "$@"; do
    printf ' %s' "$(redact_command_arg "$arg")"
  done
  printf '\n'
}

redact_command_arg() {
  arg=$1
  case "$arg" in
    *=*)
      key=${arg%%=*}
      value=${arg#*=}
      upper_key=$(printf '%s' "$key" | tr '[:lower:]' '[:upper:]')
      case "$upper_key" in
        *PASSWORD*|*SECRET*|*TOKEN*|*KEY*|*HMAC*|*DATABASE_URL*)
          if [ "$value" = "" ]; then
            printf '%s=' "$key"
          else
            printf '%s=<set:redacted>' "$key"
          fi
          return
          ;;
        *URL*)
          printf '%s=%s' "$key" "$(redact_url "$value")"
          return
          ;;
      esac
      ;;
  esac

  case "$arg" in
    *://*@*) redact_url "$arg" ;;
    *) printf '%s' "$arg" ;;
  esac
}

run_cmd() {
  name=$1
  shift
  log="$LOG_DIR/${name}.log"
  echo "[local-alpha] ==> $name"
  {
    log_command_line "$@"
    (cd "$REPO_ROOT" && "$@")
  } >"$log" 2>&1 || {
    echo "[local-alpha] failed: $name (log: $log)" >&2
    tail -80 "$log" >&2 || true
    exit 1
  }
}

start_bg() {
  name=$1
  shift
  log="$LOG_DIR/${name}.log"
  echo "[local-alpha] ==> start $name (log: $log)" >&2
  log_command_line "$@" >"$log" 2>&1
  nohup sh -c 'repo=$1; shift; cd "$repo" || exit 1; exec "$@"' sh "$REPO_ROOT" "$@" >>"$log" 2>&1 </dev/null &
  pid=$!
  echo "$name=$pid" >>"$PIDS_FILE"
  printf '%s\n' "$pid"
}

wait_http() {
  url=$1
  name=$2
  deadline=$(($(date +%s) + 90))
  while [ "$(date +%s)" -lt "$deadline" ]; do
    if curl -fsS "$url" >/dev/null 2>&1; then
      echo "[local-alpha] ready: $name $url"
      return 0
    fi
    sleep 1
  done
  fail "$name did not become ready: $url"
}

# (MOMO-316) wait_compose_healthy 폴링 헬퍼는 제거됨 —
# compose 서비스 대기는 `docker compose up -d --wait`(healthcheck 기반)가 담당한다.

assert_pid_alive() {
  pid=$1
  name=$2
  log=$3
  if ! kill -0 "$pid" 2>/dev/null; then
    echo "[local-alpha] $name exited early (log: $log)" >&2
    tail -80 "$log" >&2 || true
    exit 1
  fi
}

write_stop_script() {
  STOP_SCRIPT="$EVIDENCE_DIR/stop-local-alpha.sh"
  cat >"$STOP_SCRIPT" <<EOF
#!/usr/bin/env sh
set -eu
REPO_ROOT='$REPO_ROOT'
ENV_FILE='$ENV_FILE'
COMPOSE_OVERRIDE='$COMPOSE_OVERRIDE'
PIDS_FILE='$PIDS_FILE'

if [ -f "\$PIDS_FILE" ]; then
  awk -F= '{print \$2}' "\$PIDS_FILE" | while IFS= read -r pid; do
    if [ "\$pid" != "" ] && kill -0 "\$pid" 2>/dev/null; then
      kill "\$pid" 2>/dev/null || true
    fi
  done
fi

docker compose --env-file "\$ENV_FILE" \
  -f "\$REPO_ROOT/infra/docker-compose.yml" \
  -f "\$COMPOSE_OVERRIDE" down
EOF
  chmod +x "$STOP_SCRIPT"
  export STOP_SCRIPT
}

write_summary() {
  SUMMARY="$EVIDENCE_DIR/summary.md"
  {
    echo "# MOMO-240 Local Alpha Evidence"
    echo
    echo "- repo: $REPO_ROOT"
    echo "- git head: $(git -C "$REPO_ROOT" rev-parse --short HEAD)"
    echo "- mode: $MODE"
    echo "- hermes mode: $HERMES_MODE"
    echo "- external runtime smoke: $EXTERNAL_SMOKE"
    echo "- AWS resources: none; this runner does not call aws or create cloud resources."
    echo "- env file: $ENV_FILE"
    echo "- evidence dir: $EVIDENCE_DIR"
    echo
    echo "## URLs"
    echo
    echo "- MomoServer health: http://127.0.0.1:${PORT}/health"
    echo "- MomoServer REST base: http://127.0.0.1:${PORT}"
    echo "- Centrifugo HTTP: http://127.0.0.1:${CENT_PORT}"
    echo "- Centrifugo WebSocket: ws://127.0.0.1:${CENT_PORT}/connection/websocket"
    if [ "$HERMES_MODE" = "mock" ]; then
      echo "- mock Hermes health: http://127.0.0.1:${HERMES_PORT}/health"
      echo "- mock Hermes base: ${HERMES_BASE_URL}"
    else
      echo "- external Hermes base: $(redact_url "$HERMES_BASE_URL")"
    fi
    echo
    echo "## Env"
    echo
    for key in COMPOSE_PROJECT_NAME POSTGRES_DB POSTGRES_PORT DATABASE_URL CENT_PORT CENT_API_URL PORT HOST HERMES_BASE_URL HERMES_API_KEY CENT_API_KEY JWT_HMAC; do
      eval "value=\${$key:-}"
      printf -- "- %s: " "$key"
      print_redacted_env_value "$key" "$value"
      printf '\n'
    done
    echo
    echo "## Logs"
    echo
    echo "- docker up: $LOG_DIR/docker-up.log"
    echo "- docker ps: $LOG_DIR/docker-ps.log"
    echo "- migrate: $LOG_DIR/migrate.log"
    echo "- rls prep: $LOG_DIR/verify-rls.log"
    echo "- server: $LOG_DIR/server.log"
    echo "- relay: $LOG_DIR/relay.log"
    echo "- worker: $LOG_DIR/worker.log"
    if [ "$HERMES_MODE" = "mock" ]; then
      echo "- mock Hermes: $LOG_DIR/mock-hermes.log"
    fi
    echo "- macOS smoke: $LOG_DIR/macos-smoke.log"
    echo
    echo "## macOS Dev Launch"
    echo
    echo '```sh'
    echo "swift run --package-path clients/macOS MomoMacSmoke"
    echo '```'
    echo
    echo "> Current main has a SwiftPM macOS dev smoke target, not a packaged .app."
    echo
    echo "## Stop"
    echo
    echo '```sh'
    echo "$STOP_SCRIPT"
    echo '```'
  } >"$SUMMARY"
  export SUMMARY
}

print_plan() {
  echo "[local-alpha] mode: plan"
  echo "[local-alpha] repo: $REPO_ROOT"
  echo "[local-alpha] AWS resources: none"
  echo "[local-alpha] hermes mode: $HERMES_MODE"
  echo "[local-alpha] external runtime smoke: $EXTERNAL_SMOKE"
  if [ "$SECRET_ENV_FILE" != "" ]; then
    echo "[local-alpha] secret env: $SECRET_ENV_FILE (outside repo enforced)"
  elif [ "$HERMES_MODE" = "external" ]; then
    echo "[local-alpha] secret env: required for external Hermes"
  else
    echo "[local-alpha] secret env: generated dev-only env outside repo during execute"
  fi
  echo "[local-alpha] evidence root: $EVIDENCE_ROOT"
  echo
  if [ "$HERMES_MODE" = "external" ] && [ "$EXTERNAL_SMOKE" = "1" ]; then
    echo "Execute will delegate to scripts/verify_external_agent_provider.sh:"
    echo "  1. use .env.worktree/.env/infra/.env.example as the local stack base env"
    echo "  2. load --secret-env as EXTERNAL_AGENT_PROVIDER_ENV_FILE"
    echo "  3. require credentialed external runtime config"
    echo "  4. run provider SSE preflight"
    echo "  5. boot local MomoServer/OutboxRelay/AgentWorker and send one @agent roundtrip"
    echo "  6. write redacted external-agent-provider evidence"
    return 0
  fi
  echo "Execute will run:"
  echo "  1. docker compose up -d --wait (PG18 + Centrifugo v6, local subscribe proxy override)"
  echo "  2. scripts/migrate.sh"
  echo "  3. scripts/verify_rls.sh to prepare momo_app/momo_relay/momo_worker roles"
  echo "  4. MomoServer on http://127.0.0.1:\${PORT:-8080}"
  echo "  5. OutboxRelay and AgentWorker from SwiftPM"
  if [ "$HERMES_MODE" = "external" ] && [ "$EXTERNAL_SMOKE" = "1" ]; then
    echo "  6. delegate to scripts/verify_external_agent_provider.sh for provider SSE + momo @agent roundtrip"
  else
    echo "  6. mock Hermes locally or verify external Hermes env"
  fi
  echo "  7. swift run --package-path clients/macOS MomoMacSmoke"
  echo "  8. evidence summary with URLs, redacted env, logs, and stop command"
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    plan|--plan|--dry-run|dry-run)
      MODE=plan
      shift
      ;;
    execute|--execute)
      MODE=execute
      shift
      ;;
    --hermes)
      [ "$#" -ge 2 ] || fail "--hermes requires mock or external"
      HERMES_MODE=$2
      case "$HERMES_MODE" in mock|external) ;; *) fail "--hermes must be mock or external" ;; esac
      shift 2
      ;;
    --secret-env)
      [ "$#" -ge 2 ] || fail "--secret-env requires an absolute path"
      SECRET_ENV_FILE=$(abs_existing_file "$2")
      assert_secret_env_outside_repo "$SECRET_ENV_FILE"
      shift 2
      ;;
    --external-smoke)
      EXTERNAL_SMOKE=1
      shift
      ;;
    --evidence-root)
      [ "$#" -ge 2 ] || fail "--evidence-root requires a path"
      EVIDENCE_ROOT=$(abs_dir_path "$2")
      shift 2
      ;;
    --stop-after-smoke)
      KEEP_RUNNING=0
      shift
      ;;
    --api-proxy-host)
      [ "$#" -ge 2 ] || fail "--api-proxy-host requires a host"
      API_PROXY_HOST=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

[ "$EXTERNAL_SMOKE" = "0" ] || [ "$HERMES_MODE" = "external" ] || \
  fail "--external-smoke requires --hermes external"

case "$MODE" in
  plan)
    print_plan
    exit 0
    ;;
  execute) ;;
  *) fail "invalid mode: $MODE" ;;
esac

[ "$HERMES_MODE" = "mock" ] || [ "$SECRET_ENV_FILE" != "" ] || \
  fail "--hermes external requires --secret-env /path/outside/repo.env"

external_smoke_base_env() {
  if [ "${LOCAL_ALPHA_BASE_ENV_FILE:-}" != "" ]; then
    abs_existing_file "$LOCAL_ALPHA_BASE_ENV_FILE"
    return
  fi
  for candidate in "$REPO_ROOT/.env.worktree" "$REPO_ROOT/.env" "$REPO_ROOT/infra/.env.example"; do
    if [ -f "$candidate" ]; then
      printf '%s\n' "$candidate"
      return
    fi
  done
  fail "no base env file found for external smoke"
}

if [ "$EXTERNAL_SMOKE" = "1" ]; then
  BASE_ENV_FILE=$(external_smoke_base_env)
  echo "[local-alpha] delegating external runtime smoke"
  echo "[local-alpha] base env: $BASE_ENV_FILE"
  echo "[local-alpha] provider secret env: $SECRET_ENV_FILE"
  ENV_FILE="$BASE_ENV_FILE" \
  EXTERNAL_AGENT_PROVIDER_ENV_FILE="$SECRET_ENV_FILE" \
  EXTERNAL_AGENT_PROVIDER_REQUIRE_CREDENTIALS=1 \
    "$REPO_ROOT/scripts/verify_external_agent_provider.sh"
  exit $?
fi

RUN_ID=$(date -u '+%Y%m%dT%H%M%SZ')
EVIDENCE_DIR=$EVIDENCE_ROOT/$RUN_ID
LOG_DIR=$EVIDENCE_DIR/logs
PIDS_FILE=$EVIDENCE_DIR/pids.env
mkdir -p "$LOG_DIR"
: >"$PIDS_FILE"

if [ "$SECRET_ENV_FILE" != "" ]; then
  ENV_FILE=$SECRET_ENV_FILE
else
  write_generated_env
fi

load_env_file
write_local_centrifugo_config
write_stop_script

require_cmd docker
require_cmd curl
require_cmd swift
require_cmd python3

if [ "$HERMES_MODE" = "external" ]; then
  [ "$HERMES_BASE_URL" != "" ] || fail "HERMES_BASE_URL is required in --secret-env"
  [ "$HERMES_API_KEY" != "" ] || fail "HERMES_API_KEY is required in --secret-env"
  case "$HERMES_API_KEY" in
    change-me*|dev-insecure*) fail "HERMES_API_KEY looks like a placeholder" ;;
  esac
fi

echo "[local-alpha] evidence: $EVIDENCE_DIR"
echo "[local-alpha] env file: $ENV_FILE"
echo "[local-alpha] AWS resources: none"

# MOMO-316: --wait가 postgres/centrifugo healthcheck healthy까지 대기하므로
# 별도 wait_compose_healthy 폴링이 필요 없다. wait_http는 compose 밖의
# host 프로세스(mock Hermes/MomoServer)에만 남는다 — 이들은 compose 서비스가
# 아니라 healthcheck를 붙일 수 없다.
run_cmd docker-up docker compose --env-file "$ENV_FILE" \
  -f "$REPO_ROOT/infra/docker-compose.yml" \
  -f "$COMPOSE_OVERRIDE" up -d --wait
run_cmd docker-ps docker compose --env-file "$ENV_FILE" \
  -f "$REPO_ROOT/infra/docker-compose.yml" \
  -f "$COMPOSE_OVERRIDE" ps

run_cmd migrate sh "$REPO_ROOT/scripts/migrate.sh"
run_cmd verify-rls sh "$REPO_ROOT/scripts/verify_rls.sh"

if [ "$HERMES_MODE" = "mock" ]; then
  MOCK_PID=$(start_bg mock-hermes python3 "$REPO_ROOT/scripts/mock_hermes.py" \
    --host 127.0.0.1 --port "$HERMES_PORT")
  wait_http "http://127.0.0.1:${HERMES_PORT}/health" "mock Hermes"
else
  echo "[local-alpha] external Hermes env present: $(redact_url "$HERMES_BASE_URL")"
fi

APP_DATABASE_URL=${APP_DATABASE_URL:-postgres://momo_app:momo_app_dev_pw@localhost:${POSTGRES_PORT}/${POSTGRES_DB}}
RELAY_DATABASE_URL=${RELAY_DATABASE_URL:-postgres://momo_relay:momo_relay_dev_pw@localhost:${POSTGRES_PORT}/${POSTGRES_DB}}
WORKER_DATABASE_URL=${WORKER_DATABASE_URL:-postgres://momo_worker:momo_worker_dev_pw@localhost:${POSTGRES_PORT}/${POSTGRES_DB}}

SERVER_PID=$(start_bg server env \
  DATABASE_URL="$APP_DATABASE_URL" \
  CENT_API_URL="$CENT_API_URL" \
  CENT_API_KEY="$CENT_API_KEY" \
  CENT_TOKEN_HMAC="$CENT_TOKEN_HMAC" \
  JWT_HMAC="$JWT_HMAC" \
  PORT="$PORT" \
  HOST="$HOST" \
  swift run --package-path server MomoServer)
wait_http "http://127.0.0.1:${PORT}/health" "MomoServer"

RELAY_PID=$(start_bg relay env \
  RELAY_DATABASE_URL="$RELAY_DATABASE_URL" \
  DATABASE_URL="$RELAY_DATABASE_URL" \
  CENT_API_URL="$CENT_API_URL" \
  CENT_API_KEY="$CENT_API_KEY" \
  RELAY_POLL_INTERVAL_MS="${RELAY_POLL_INTERVAL_MS:-100}" \
  swift run --package-path relay/OutboxRelay OutboxRelay)

WORKER_PID=$(start_bg worker env \
  RELAY_DATABASE_URL="$WORKER_DATABASE_URL" \
  DATABASE_URL="$WORKER_DATABASE_URL" \
  CENT_API_URL="$CENT_API_URL" \
  CENT_API_KEY="$CENT_API_KEY" \
  HERMES_BASE_URL="$HERMES_BASE_URL" \
  HERMES_API_KEY="$HERMES_API_KEY" \
  WORKER_POLL_INTERVAL_MS="${WORKER_POLL_INTERVAL_MS:-100}" \
  swift run --package-path workers/AgentWorker AgentWorker)

sleep 5
assert_pid_alive "$SERVER_PID" server "$LOG_DIR/server.log"
assert_pid_alive "$RELAY_PID" relay "$LOG_DIR/relay.log"
assert_pid_alive "$WORKER_PID" worker "$LOG_DIR/worker.log"

run_cmd macos-smoke swift run --package-path clients/macOS MomoMacSmoke

write_summary

echo
echo "[local-alpha] READY"
echo "[local-alpha] MomoServer: http://127.0.0.1:${PORT}/health"
echo "[local-alpha] Centrifugo: ws://127.0.0.1:${CENT_PORT}/connection/websocket"
if [ "$HERMES_MODE" = "mock" ]; then
  echo "[local-alpha] mock Hermes: http://127.0.0.1:${HERMES_PORT}/health"
else
  echo "[local-alpha] external Hermes: $(redact_url "$HERMES_BASE_URL")"
fi
echo "[local-alpha] macOS dev launch: swift run --package-path clients/macOS MomoMacSmoke"
echo "[local-alpha] evidence summary: $SUMMARY"
echo "[local-alpha] logs: $LOG_DIR"
echo "[local-alpha] stop: $STOP_SCRIPT"

if [ "$KEEP_RUNNING" = "0" ]; then
  echo "[local-alpha] --stop-after-smoke requested; stopping local alpha stack"
  "$STOP_SCRIPT"
fi
