import type { LucideIcon } from "lucide-react";
import {
  Clock,
  Coffee,
  Flag,
  Hash,
  Leaf,
  Lightbulb,
  MapPin,
  Smile,
  Trophy,
} from "lucide-react";

// =============================================================================
// Same-origin emoji catalog (#1742).
//
// Generated by `clients/web/scripts/extract-emoji-catalog.mjs` from
// emojibase-data compact(en) + the iamcal (Slack) shortcode preset. Runtime
// never imports emojibase-data. Re-run the script after bumping that
// devDependency.
// =============================================================================

export const EMOJI_CATEGORY_IDS = [
  "people",
  "nature",
  "foods",
  "activity",
  "places",
  "objects",
  "symbols",
  "flags",
] as const;

export type EmojiCategoryId = (typeof EMOJI_CATEGORY_IDS)[number];

export type CatalogEmoji = {
  glyph: string;
  name: string;
  shortcodes: string[];
  keywords: string[];
  category: EmojiCategoryId;
  skins?: string[];
};

type RawCatalog = {
  v: number;
  items: Array<
    [string, string, string[], string[], number] | [string, string, string[], string[], number, string[]]
  >;
};

export function parseCatalog(raw: RawCatalog): CatalogEmoji[] {
  return raw.items.flatMap((row) => {
    const [glyph, name, shortcodes, keywords, categoryIndex, skins] = row;
    const category = EMOJI_CATEGORY_IDS[categoryIndex];
    if (!glyph || !name || !category) return [];
    const entry: CatalogEmoji = { glyph, name, shortcodes, keywords, category };
    if (skins && skins.length === 5) entry.skins = skins;
    return [entry];
  });
}

let catalogPromise: Promise<CatalogEmoji[]> | undefined;

export function loadCatalog(): Promise<CatalogEmoji[]> {
  catalogPromise ??= import("./emojiCatalog.json").then(
    (mod) => parseCatalog(mod.default as RawCatalog),
    (error) => {
      catalogPromise = undefined;
      throw error;
    }
  );
  return catalogPromise;
}

/** Strip VS16 so 👍 and 👍️ compare as the same picker identity. */
export function foldEmoji(value: string): string {
  return value.replaceAll("\uFE0F", "");
}

export function resolveCatalogEmoji(
  entries: readonly CatalogEmoji[],
  glyph: string
): CatalogEmoji | undefined {
  const folded = foldEmoji(glyph);
  return (
    entries.find((entry) => foldEmoji(entry.glyph) === folded) ??
    entries.find((entry) => entry.skins?.some((skin) => foldEmoji(skin) === folded))
  );
}

export type SkinTone = 0 | 1 | 2 | 3 | 4 | 5;

export function displayGlyph(entry: CatalogEmoji, tone: SkinTone): string {
  if (tone === 0 || !entry.skins) return entry.glyph;
  return entry.skins[tone - 1] ?? entry.glyph;
}

export const EMOJI_CATEGORY_TABS: ReadonlyArray<{
  id: "frequent" | EmojiCategoryId;
  label: string;
  Icon: LucideIcon;
}> = [
  { id: "frequent", label: "자주 씀", Icon: Clock },
  { id: "people", label: "사람", Icon: Smile },
  { id: "nature", label: "자연", Icon: Leaf },
  { id: "foods", label: "음식", Icon: Coffee },
  { id: "activity", label: "활동", Icon: Trophy },
  { id: "places", label: "장소", Icon: MapPin },
  { id: "objects", label: "물건", Icon: Lightbulb },
  { id: "symbols", label: "기호", Icon: Hash },
  { id: "flags", label: "깃발", Icon: Flag },
];
