import type { LucideIcon } from "lucide-react";
import {
  Clock,
  Coffee,
  Flag,
  Hash,
  Leaf,
  Lightbulb,
  MapPin,
  Smile,
  Trophy,
} from "lucide-react";

// =============================================================================
// Same-origin emoji catalog (#1742).
//
// Generated by `clients/web/scripts/extract-emoji-catalog.mjs` from
// emojibase-data compact(en) + the iamcal (Slack) shortcode preset. Runtime
// never imports emojibase-data. Re-run the script after bumping that
// devDependency.
// =============================================================================

export const EMOJI_CATEGORY_IDS = [
  "people",
  "nature",
  "foods",
  "activity",
  "places",
  "objects",
  "symbols",
  "flags",
] as const;

export type EmojiCategoryId = (typeof EMOJI_CATEGORY_IDS)[number];

export type CatalogEmoji = {
  glyph: string;
  name: string;
  shortcodes: string[];
  keywords: string[];
  category: EmojiCategoryId;
  skins?: string[];
};

type RawCatalog = {
  v: number;
  items: Array<
    [string, string, string[], string[], number] | [string, string, string[], string[], number, string[]]
  >;
};

export function parseCatalog(raw: RawCatalog): CatalogEmoji[] {
  return raw.items.flatMap((row) => {
    const [glyph, name, shortcodes, keywords, categoryIndex, skins] = row;
    const category = EMOJI_CATEGORY_IDS[categoryIndex];
    if (!glyph || !name || !category) return [];
    const entry: CatalogEmoji = { glyph, name, shortcodes, keywords, category };
    if (skins && skins.length === 5) entry.skins = skins;
    return [entry];
  });
}

// -----------------------------------------------------------------------------
// 카탈로그 적재와 **재시도** (design-review #1930 H-3).
//
// 앞 판은 `import()` 하나였고, 실패하면 `catalogPromise` 를 지워서 「다음에 다시
// 부르면 다시 싣는다」고 적었다. **그것은 참이 아니었다.** 실패한 dynamic import
// 는 브라우저 모듈 맵에 그 specifier 의 실패로 **영구히** 기억되므로, 같은
// specifier 로 다시 부르면 네트워크에 아무것도 안 나가고 기억된 실패가 즉시
// 되던져진다(리뷰 실측: 청크를 끊은 세션에서 요청은 평생 1건, 피커의 「다시
// 시도」도 컴포저의 것도 배너를 못 걷었다).
//
// 그래서 재시도는 **다른 문**을 쓴다: 같은 파일을 자산 URL 로 가리켜
// `fetch(..., { cache: "reload" })` 로 다시 받는다. 모듈 맵도 HTTP 캐시도 지나지
// 않으므로 실제 요청이 나가고, 서버가 살아났으면 목록이 되살아난다. 두 표면이
// 같은 이 함수를 부르므로 피커와 컴포저의 「다시 시도」가 한 번에 참이 된다
// (문장을 `copy.ts` 한 자리에 모은 그 이유와 같다).
//
// 첫 적재를 `fetch` 로 통일하지 않는 이유: `import()` 는 번들러가 이 청크를
// 코드 분할·프리로드·해시 무효화의 정본으로 다루는 자리이고, 실패하지 않는
// 평상시 경로를 자산 URL 수동 조립으로 바꾸면 그 계약을 이 파일이 대신 지게
// 된다. 바뀐 것은 「실패한 뒤」뿐이다.
//
// 대가는 하나, 정직하게 적는다: 빌드 산출물에 같은 데이터가 두 벌 실린다
// (`emojiCatalog-*.js` 청크 + `emojiCatalog-*.json` 자산). **내려받는 것은 언제나
// 한 벌**이고 두 번째는 첫 벌이 죽었을 때만 두드리는 문이라 부팅 예산은 그대로다.
// -----------------------------------------------------------------------------

/** 재시도가 두드리는 문. 번들러가 이 파일을 자산으로 함께 낸다. */
const CATALOG_URL = new URL("./emojiCatalog.json", import.meta.url).href;

let catalogPromise: Promise<CatalogEmoji[]> | undefined;
/** 모듈 맵이 이 specifier 를 실패로 기억한다 — 이후 적재는 `fetch` 로 간다. */
let importFailed = false;

async function importCatalog(): Promise<CatalogEmoji[]> {
  const mod = await import("./emojiCatalog.json");
  return parseCatalog(mod.default as RawCatalog);
}

async function refetchCatalog(): Promise<CatalogEmoji[]> {
  const response = await fetch(CATALOG_URL, { cache: "reload" });
  if (!response.ok) throw new Error(`emoji catalog ${response.status}`);
  return parseCatalog((await response.json()) as RawCatalog);
}

export function loadCatalog(): Promise<CatalogEmoji[]> {
  catalogPromise ??= (importFailed ? refetchCatalog() : importCatalog()).catch(
    (error: unknown) => {
      catalogPromise = undefined;
      importFailed = true;
      throw error;
    }
  );
  return catalogPromise;
}

/** 시험 전용. 모듈 맵 흉내까지 지우고 첫 적재 상태로 되돌린다. */
export function resetCatalogForTests(): void {
  catalogPromise = undefined;
  importFailed = false;
}

/** Strip VS16 so 👍 and 👍️ compare as the same picker identity. */
export function foldEmoji(value: string): string {
  return value.replaceAll("\uFE0F", "");
}

export function resolveCatalogEmoji(
  entries: readonly CatalogEmoji[],
  glyph: string
): CatalogEmoji | undefined {
  const folded = foldEmoji(glyph);
  return (
    entries.find((entry) => foldEmoji(entry.glyph) === folded) ??
    entries.find((entry) => entry.skins?.some((skin) => foldEmoji(skin) === folded))
  );
}

export type SkinTone = 0 | 1 | 2 | 3 | 4 | 5;

export function displayGlyph(entry: CatalogEmoji, tone: SkinTone): string {
  if (tone === 0 || !entry.skins) return entry.glyph;
  return entry.skins[tone - 1] ?? entry.glyph;
}

export const EMOJI_CATEGORY_TABS: ReadonlyArray<{
  id: "frequent" | EmojiCategoryId;
  label: string;
  Icon: LucideIcon;
}> = [
  { id: "frequent", label: "자주 씀", Icon: Clock },
  { id: "people", label: "사람", Icon: Smile },
  { id: "nature", label: "자연", Icon: Leaf },
  { id: "foods", label: "음식", Icon: Coffee },
  { id: "activity", label: "활동", Icon: Trophy },
  { id: "places", label: "장소", Icon: MapPin },
  { id: "objects", label: "물건", Icon: Lightbulb },
  { id: "symbols", label: "기호", Icon: Hash },
  { id: "flags", label: "깃발", Icon: Flag },
];
